import Foundation

public enum IQTablesEmit {

    static let banner = """
        // Generated by IQTablesEmit from the Swift grids in LLM/Quantize.
        // Do not hand-edit: `gadeon --emit-iq-tables` rewrites it, and
        // IQTablesTests fails when this file and those grids disagree.


        """

    public static func header() -> String {
        var out = banner
        out += hex("iq1s_grid_gpu", IQ1Grid.gpu)
        out += hex("iq2xxs_grid_u32", halves(IQ2Grid.xxs))
        out += hex("iq2xs_grid_u32", halves(IQ3Grid.xs2))
        out += hex("iq2s_grid_u32", halves(IQ3Grid.s2))
        out += hex("iq3xxs_grid", IQ3Grid.xxs3)
        out += hex("iq3s_grid", IQ3Grid.s3)
        out += wide("uchar", "ksigns_iq2xs",
                    IQ2Grid.ksigns.map { v in "\(v)" }, perLine: 16)
        out += flat("uchar", "kmask_iq2xs",
                    IQ2Grid.kmask.map { v in "\(v)" })
        out += flat("char", "kvalues_iq4nl",
                    IQ3Grid.nl4.map { v in "\(v)" })
        while out.hasSuffix("\n\n") { out.removeLast() }
        return out
    }

    static func halves(_ values: [UInt64]) -> [UInt32] {
        var out: [UInt32] = []
        out.reserveCapacity(values.count * 2)
        for v in values {
            out.append(UInt32(truncatingIfNeeded: v))
            out.append(UInt32(truncatingIfNeeded: v >> 32))
        }
        return out
    }

    private static func hex(_ name: String, _ values: [UInt32]) -> String {
        wide("uint", name,
             values.map { v in String(format: "0x%08x", v) }, perLine: 6)
    }

    private static func wide(_ type: String, _ name: String,
                             _ values: [String], perLine: Int) -> String {
        var out = "constant \(type) \(name)[\(values.count)] = {\n"
        var i = 0
        while i < values.count {
            let end = min(i + perLine, values.count)
            out += "    " + values[i..<end].joined(separator: ", ") + ",\n"
            i = end
        }
        return out + "};\n\n"
    }

    private static func flat(_ type: String, _ name: String,
                             _ values: [String]) -> String {
        "constant \(type) \(name)[\(values.count)] = {"
            + values.joined(separator: ", ") + "};\n\n"
    }

}
